export const GET_TODAY = 'GET_TODAY'
export const SET_TODAY = 'SET_TODAY'


export const GET_DEFAULT_DATE = 'GET_DEFAULT_DATE'
export const SET_DEFAULT_DATE = 'SET_DEFAULT_DATE'

export const SET_SELECTED_DATE = 'SET_SELECTED_DATE'
export const SET_SELECTED_MONTH = 'SET_SELECTED_MONTH'
export const SET_SELECTED_YEAR = 'SET_SELECTED_YEAR'