const GET_MESSAGE_LIST_SUCCESS = 'GET_MESSAGE_LIST_SUCCESS';
const SEND_MESSAGE_SUCCESS= 'SEND_MESSAGE_SUCCESS';

const GET_MESSAGE_LIST_FAIL = "GET_MESSAGE_LIST_FAIL";
const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL";


const messageconstant = {
    GET_MESSAGE_LIST_SUCCESS,
    GET_MESSAGE_LIST_FAIL,
    SEND_MESSAGE_SUCCESS,
    SEND_MESSAGE_FAIL,
}

export default messageconstant;

